export const events = [
    {
        id: 1,
        title: "React Native EU 2024",
        slug: "react-native-eu-2024",
        location: "Wrocław, Poland",
        date: "September 5-6, 2024",
        time: "09:00 AM - 06:00 PM",
        image: "/images/event1.png",
    },
    {
        id: 2,
        title: "Next.js Conf 2024",
        slug: "nextjs-conf-2024",
        location: "San Francisco, CA",
        date: "October 24, 2024",
        time: "10:00 AM - 04:00 PM",
        image: "/images/event2.png",
    },
    {
        id: 3,
        title: "PyCon US 2025",
        slug: "pycon-us-2025",
        location: "Pittsburgh, PA",
        date: "May 14-22, 2025",
        time: "08:00 AM - 05:00 PM",
        image: "/images/event3.png",
    },
    {
        id: 4,
        title: "AI World Summit",
        slug: "ai-world-summit-2024",
        location: "London, UK",
        date: "November 12-13, 2024",
        time: "09:30 AM - 05:30 PM",
        image: "/images/event4.png",
    },
    {
        id: 5,
        title: "Vue.js Amsterdam",
        slug: "vuejs-amsterdam-2025",
        location: "Amsterdam, Netherlands",
        date: "February 15-16, 2025",
        time: "09:00 AM - 06:00 PM",
        image: "/images/event5.png",
    },
    {
        id: 6,
        title: "AWS re:Invent",
        slug: "aws-reinvent-2024",
        location: "Las Vegas, NV",
        date: "December 2-6, 2024",
        time: "08:00 AM - 08:00 PM",
        image: "/images/event6.png",
    },
];
